# This workflow runs tests

name: Test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    strategy:
      matrix:
        java: [ '11', '17' ]
    
    name: Test - Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Run Tests
      run: ./gradlew check --continue --warn
      timeout-minutes: 4

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Java-${{ matrix.java }}-Tests
        path: /home/runner/work/coroutines/coroutines/queue/build/reports/
        retention-days: 60
        if-no-files-found: error
      timeout-minutes: 1
