# This workflow runs tests

name: Test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    name: Test Report
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Run Tests
      run: ./gradlew check --continue --warn
      timeout-minutes: 4

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: CoroutineQueue-TestReports
        path: /home/runner/work/coroutines/coroutines/queue/build/reports/
        retention-days: 21
        if-no-files-found: error
      timeout-minutes: 1
